{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.minio.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.minio.service.apiPort }}
      targetPort: {{ .Values.minio.service.apiPort }}
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: {{ .Values.minio.service.consolePort }}
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: minio
  replicas: {{ .Values.minio.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: object-storage
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
              protocol: TCP
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
              protocol: TCP
          args:
            {{- toYaml .Values.minio.args | nindent 12 }}
          env:
            {{- toYaml .Values.minio.env | nindent 12 }}
          {{- if .Values.minio.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.minio.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.minio.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.minio.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          {{- if .Values.minio.persistence.enabled }}
          volumeMounts:
            - name: minio-data
              mountPath: {{ .Values.minio.persistence.mountPath }}
          {{- end }}
  {{- if .Values.minio.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.minio.persistence.storageClass }}
        storageClassName: {{ .Values.minio.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size }}
  {{- end }}
{{- end }}
